import { test } from 'node:test';
import assert from 'node:assert/strict';
import XLSX from 'xlsx';
import { readWorkbook, parseTransactions, parseSummaryTotals, checkReportDetails } from '../src/accounting/workbook.js';
import { splitRows } from '../src/accounting/classify.js';
import { OPTIONS } from '../src/accounting/settings.js';

// Layout copied from a real Xola "Recognized Earnings Report" (Amsterdam, Aug 2026).
function recognizedFile() {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([
    ['Report Name', 'Recognized Earnings Report'], [null, null], ['Generated By', null], ['Name', 'Accountant'],
    ['Company', 'Amsterdam Tours'], ['Generated Date', 'Sep 26, 2026, 1:44 PM'], [null, null], ['Filters', null],
    ['Realized Date is between', '8/1/26, 8/31/26'],
  ]), 'Report Details');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([
    ['Summary Report', '(1 Aug, 2026 - 31 Aug, 2026)'], [],
    ['Method', 'Gross', 'Processing Fee', 'Service Fee', 'Guest Fee', 'Net'],
    ['Electronic', 76.95, 0, 0, 0, 76.95], ['Other', 25, 0, 0, 0, 25],
  ]), 'Summary');
  const H = ['Transaction ID', 'Purchase ID', 'Confirmation Code', 'Transaction Date', 'Arrival Date', 'Realized Date', 'Item', 'Package', 'Customer Name', 'Currency', 'Recognized In Period',
    'Previously Collected - Gross', 'Previously Collected - Processing Fee', 'Previously Collected - Service Fee', 'Previously Collected - Net',
    'Collected In Period - Gross', 'Collected In Period - Processing Fee', 'Collected In Period - Service Fee', 'Collected In Period - Net', 'Balance', 'Source', 'Method', 'CC Brand', 'Tags', 'Card fee'];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([
    H,
    ['t1', 'p1', '4a89c8', '2026-08-12', '30-Aug-2026', '2026-08-30', 'Ghost Tour', null, 'A', 'EUR', 52.7, 0, 0, 0, 0, 52.7, 0, 0, 52.7, 172.16, 'Get Your Guide', 'Electronic', null, 'GYG', 1.2],
    ['t2', 'p2', 'a7a2f4', '2026-03-05', '23-Aug-2026', '2026-08-23', 'Walk', null, 'B', 'EUR', 23, 23, 0, 0, 23, 0, 0, 0, 0, 172.16, 'office', 'Other', null, 'Imported', null],
    ['t3', 'p3', 'a7a2f5', '2026-03-05', '23-Aug-2026', '2026-08-23', 'Walk', null, 'C', 'EUR', 2, 2, 0, 0, 2, 0, 0, 0, 0, 172.16, 'office', 'Other', null, 'Imported', null],
    ['t4', 'p4', '3e132d', '2026-05-28', '02-Aug-2026', '2026-08-02', 'Ghost Tour', null, 'D', 'EUR', 1.54, 1.54, 0, 0, 1.54, 0, 0, 0, 0, 172.16, 'Get Your Guide', 'Electronic', null, 'GYG', null],
    ['t5', 'p5', '3e132e', '2026-05-28', '02-Aug-2026', '2026-08-02', 'Ghost Tour', null, 'E', 'EUR', 22.71, 22.71, 0, 0, 22.71, 0, 0, 0, 0, 172.16, 'office', 'Electronic', null, '', null],
  ]), 'Transactions');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

test('Recognized Earnings layout: Net = "Recognized In Period", ties to Summary Net', () => {
  const wb = readWorkbook(recognizedFile());
  const rows = parseTransactions(wb);
  assert.equal(rows.length, 5);
  assert.equal(rows[0].net, 5270);
  assert.equal(rows[0].gross, 5270);
  assert.equal(rows[0].payoutDate, '');
  const sum = rows.reduce((t, r) => t + r.net, 0);
  assert.equal(sum, parseSummaryTotals(wb).net); // 101.95
});

test('Recognized Earnings: office paid by card counts, office "Other" is left out (byMethod)', () => {
  const saved = OPTIONS.recognizedOfficeRule;
  OPTIONS.recognizedOfficeRule = 'byMethod';
  try {
    const rows = parseTransactions(readWorkbook(recognizedFile()));
    const { included, office } = splitRows(rows, 'Amsterdam Tours');
    assert.equal(office.length, 2);
    assert.equal(included.reduce((t, r) => t + r.net, 0), 5270 + 154 + 2271);
  } finally {
    OPTIONS.recognizedOfficeRule = saved;
  }
});

test('Recognized Earnings: "include" counts every office row', () => {
  const saved = OPTIONS.recognizedOfficeRule;
  OPTIONS.recognizedOfficeRule = 'include';
  try {
    const rows = parseTransactions(readWorkbook(recognizedFile()));
    const { office } = splitRows(rows, 'Amsterdam Tours');
    assert.equal(office.length, 0);
  } finally {
    OPTIONS.recognizedOfficeRule = saved;
  }
});

test('Report Details: Recognized file passes as earnings and is refused in the Cash Flow slot', () => {
  const buf = recognizedFile();
  assert.equal(checkReportDetails(buf, 'earnings', '2026-08-01', '2026-08-31', { company: 'Amsterdam Tours' }).pass, true);
  const asCash = checkReportDetails(buf, 'account', '2026-08-01', '2026-08-31', { company: 'Amsterdam Tours' });
  assert.equal(asCash.pass, false);
  assert.match(asCash.message, /Recognized Earnings/);
});
