import ExcelJS from 'exceljs';
import { fromCents } from './money.js';

// Workbook writers (styling kept from the original importFile.js).
const FONT = 'Arial';
const NAVY = 'FF1F3864';
const WHITE = 'FFFFFFFF';
const MONEY = '#,##0.00;(#,##0.00)';

function sheet(wb, name, headers, widths) {
  const ws = wb.addWorksheet(name, { views: [{ state: 'frozen', ySplit: 1 }] });
  const hr = ws.addRow(headers);
  hr.eachCell((cell) => {
    cell.font = { name: FONT, bold: true, color: { argb: WHITE }, size: 11 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
  });
  ws.columns = widths.map((width) => ({ width }));
  return ws;
}

function addRow(ws, values, moneyCols = []) {
  const row = ws.addRow(values);
  row.eachCell({ includeEmpty: true }, (cell) => {
    if (!cell.font || !cell.font.name) cell.font = { name: FONT, size: 10 };
  });
  for (const c of moneyCols) row.getCell(c).numFmt = MONEY;
  return row;
}

const book = () => {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'GATP Solutions';
  return wb;
};
const buf = async (wb) => Buffer.from(await wb.xlsx.writeBuffer());
const money = (c) => (c ? fromCents(c) : null);

// QBO / SaasAnt journal import: *JournalNo, *JournalDate, *AccountName, *Debits, *Credits, Description, Class
export async function writeJournalXlsx(lines) {
  const wb = book();
  const ws = sheet(
    wb,
    'Journal Entry',
    ['*JournalNo', '*JournalDate', '*AccountName', '*Debits', '*Credits', 'Description', 'Class'],
    [16, 13, 44, 14, 14, 52, 38]
  );
  for (const l of lines) {
    addRow(ws, [l.journalNo, l.journalDate, l.account, money(l.debit), money(l.credit), l.description, l.class], [4, 5]);
  }
  return buf(wb);
}

// Office bookings excluded from the journal (Source = office, blank Payout Date).
export async function writeOfficeXlsx(rows, review = []) {
  const wb = book();
  const ws = sheet(
    wb,
    'Office bookings',
    ['Location', 'Transaction Date', 'Arrival Date', 'Customer Name', 'Item', 'Gross', 'Net', 'Method', 'Confirmation Code', 'Currency'],
    [32, 15, 13, 26, 36, 12, 12, 14, 20, 10]
  );
  for (const r of rows) {
    addRow(
      ws,
      [r.location, r.transactionDate, r.arrivalDate, r.customerName, r.item, fromCents(r.gross), fromCents(r.net), r.method, r.confirmationCode, r.currency],
      [6, 7]
    );
  }
  if (!rows.length) addRow(ws, ['No office bookings with a blank Payout Date this month.']);

  // Bookings whose Source is not in the SOP table (e.g. Tiqets, blank): left out
  // of the journal and listed here for the Controller.
  const rs = sheet(
    wb,
    'Source review',
    ['Location', 'Source', 'Transaction Date', 'Arrival Date', 'Customer Name', 'Item', 'Gross', 'Net', 'Payout Date', 'Confirmation Code', 'Currency'],
    [32, 14, 15, 13, 26, 36, 12, 12, 13, 20, 10]
  );
  for (const r of review) {
    addRow(
      rs,
      [r.location, r.source || '(blank)', r.transactionDate, r.arrivalDate, r.customerName, r.item, fromCents(r.gross), fromCents(r.net), r.payoutDate, r.confirmationCode, r.currency],
      [7, 8]
    );
  }
  if (!review.length) addRow(rs, ['No bookings with a Source outside the SOP table this month.']);
  return buf(wb);
}

function fmtValue(v, unit) {
  if (v === null || v === undefined) return '';
  if (unit === 'money' && typeof v === 'number') return fromCents(v);
  return v;
}

// CHECKS-YYYY-MM.xlsx: every check result, run date, user, FX rates, accepted diffs.
export async function writeChecksXlsx({ month, runDate, user, journals, fxRates = [], acceptedDiffs = [] }) {
  const wb = book();

  const info = sheet(wb, 'Run', ['Field', 'Value'], [24, 60]);
  addRow(info, ['Month', month]);
  addRow(info, ['Run date', runDate ? new Date(runDate).toISOString() : '']);
  addRow(info, ['Generated at', new Date().toISOString()]);
  addRow(info, ['Generated by', user || '']);
  for (const [key, j] of Object.entries(journals)) {
    if (!j) continue;
    addRow(info, [`${key} journal`, `${j.journalNo || ''} · ${j.status || 'not built'}${j.generatedAt ? ` · built ${new Date(j.generatedAt).toISOString()}` : ''}`]);
  }

  const ws = sheet(
    wb,
    'Checks',
    ['Journal', 'Check', 'Location', 'Name', 'Expected', 'Actual', 'Diff', 'Result', 'Note'],
    [10, 7, 32, 48, 16, 16, 12, 12, 60]
  );
  for (const [key, j] of Object.entries(journals)) {
    for (const c of j?.checks || []) {
      const accepted = !c.pass && acceptedDiffs.some((a) => a.journal === key && a.checkId === c.id && a.location === c.location);
      const row = addRow(ws, [
        key,
        c.id,
        c.location,
        c.name,
        fmtValue(c.expected, c.unit),
        fmtValue(c.actual, c.unit),
        fmtValue(c.diff, c.unit),
        c.pass ? 'PASS' : c.hardStop ? 'HARD STOP' : accepted ? 'ACCEPTED' : 'FAIL',
        c.note || '',
      ]);
      if (c.unit === 'money') for (const i of [5, 6, 7]) row.getCell(i).numFmt = MONEY;
      if (!c.pass) row.getCell(8).font = { name: FONT, size: 10, bold: true, color: { argb: accepted ? 'FFB45309' : 'FFB91C1C' } };
    }
  }

  const fx = sheet(wb, 'FX rates', ['Location', 'Currency', 'Date', 'Rate (USD per unit)', 'Rate source', 'Used by', 'Entered by', 'Entered at'], [32, 10, 16, 18, 34, 20, 30, 24]);
  for (const r of fxRates) {
    const origin = r.origin === 'ecb' ? 'ECB market rate (suggested, confirmed by user)' : 'Entered by user (banked rate)';
    addRow(fx, [r.location, r.currency, r.date || 'no date', r.rate, origin, (r.sources || []).join(', '), r.enteredBy || '', r.enteredAt ? new Date(r.enteredAt).toISOString() : '']);
  }
  if (!fxRates.length) addRow(fx, ['No foreign-currency rows this month.']);

  const acc = sheet(wb, 'Accepted differences', ['Journal', 'Check', 'Location', 'Diff', 'Reason', 'User', 'At'], [10, 7, 32, 14, 60, 30, 24]);
  for (const a of acceptedDiffs) {
    addRow(acc, [a.journal, a.checkId, a.location, a.diff ?? '', a.reason, a.user, a.at ? new Date(a.at).toISOString() : '']);
  }
  if (!acceptedDiffs.length) addRow(acc, ['None.']);

  return buf(wb);
}
